version: '3.8'

services:
  redis:    
    image: redis:latest    
    container_name: redis    
    command: ["redis-server", "--appendonly", "yes"]    
    volumes:      
      - ./database/redis:/data    
    ports:      
      - 6379:6379
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - "./database/mongodb:/data/db:rw"      
