
START TRANSACTION;

CREATE TABLE "Task" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "name" text NOT NULL,
    "description" text NOT NULL,
    "status_id"  integer NOT NULL,
    CONSTRAINT "PK_Task" PRIMARY KEY ("id"),
    CONSTRAINT "FK_Task_Sttus_status_id" FOREIGN KEY ("status_id") REFERENCES "Status" ("id")
);

COMMIT;